### ISSUE TITLE
과제 제출 문의

### ISSUE THREAD

**Issue by Minji1234** [SNUCSE-CTA/DAF#11]
2014-14966

안녕하세요? 과제 제출과 관련하여 질문이 있습니다.
팀별로 과제를 한 후 같은 소스코드를 제출해도 되는 것으로 알고 있는데, 레포트도 하나만 쓴 후 나머지 팀원이 같은 레포트를 제출해도 되는지 궁금합니다.
즉 과제로 제출하는 폴더 내부에 포함되는 main.cpp와 report.pdf, images1.jpg와 images2.jpg 파일 모두가 같은 팀원이라면 같은 내용으로 통일해서 제출해도 되나요?
감사합니다.

**Comment by ctaroot** [comment]
팀원당 한 명만 소스 코드와 레포트를 제출해야 합니다.
