### ISSUE TITLE
수행시간 기준 질문

### ISSUE THREAD

**Issue by cksgml** [SNUCSE-CTA/DAF#12]
2014-12142

이번 과제 채점기준에 average total time per query가 있는데요,
수행시간 측정은 작동되는 환경에 따라 달라질것 같아서 어느 기준으로 생각해야할지 궁급합니다. 
감사합니다.

**Comment by ctaroot** [comment]
일단 최대한 학생 분 컴퓨터로 돌려보시고, 보내주세요. 만약 제가 채점한 결과가 학생분 것과 다르면 그 때 찾아와주세요. 모든 학생 들의 환경을 다 고려하기는 현실적으로 힘들 것 같네요.
