### ISSUE TITLE
input query 관련 질문

### ISSUE THREAD

**Issue by cksgml** [SNUCSE-CTA/DAF#13]
2014-12142

97 60011.8 60023.1 12025942 0 1
98 42.0499 43.2624 8320 100000 0

이런식으로 출력되는 것에서 
마지막에 해당하는 숫자가 etl에 올려주신 파일에서 "is it solved?" 라고 표현하셨는데요,
이게 embedding 을 하나라도 찾았는지 여부인지 아니면
큰 그래프에서 input query의 embedding이 없다는 것을 확신하게 되는 경우에도 1이 나오는지 궁금합니다.
그리고 이번 과제의 모든 input query들은 모두 주어진 큰 그래프에서 embedding이 존재하는 query들인지 궁금합니다.

**Comment by ctaroot** [comment]
input query의 embedding이 없다는 것을 확신하게 되는 경우에도 1이 나옵니다.
이번 과제의 모든 input query들은 모두 data graph에서 embedding이 존재하는 query들입니다.
