### ISSUE TITLE
requirements 관련 질문

### ISSUE THREAD

**Issue by theNocturni** [SNUCSE-CTA/DAF#14]
2017-14851

Your algorithm have to be different from a given algorithm on github.

라고 requirements에 써있는데 차이에 최소한의 기준이 있나요?

예를 들어 프로그램의 큰 틀은 같지만 root를 선택하는 기준이 달라진다던가 몇몇 케이스에 대한 보강이 이루어지는 정도여도 다른 알고리즘으로 인정받는 것인가요?

**Comment by ctaroot** [comment]
[1] 루트 선별 기준이 다르다면 당연히 다른 과정의 알고리즘 입니다.
[2] 특정 케이스까지 고려해서 과정 자체가 달라진다면 물론 다른 알고리즘입니다.
