### ISSUE TITLE
과제 채점 기준 관련 질문.

### ISSUE THREAD

**Issue by KimEoJin1** [SNUCSE-CTA/DAF#15]
2019-90988

저희가 비교적 간단하게 만든 DAG 코드를 채점 프로그램을 사용해서 점수를 보았을 때 만점이 나왔는데, 추가로 이를 발전시킬 방법을 찾아야 하나요? 이대로 보고서와 프로그램을 제출해도 감점이 없는지 여쭤보고 싶습니다.

감사합니다.

**Comment by ctaroot** [comment]
만점이 나오셨으면 그냥 보내셔도 상관 없을 것 같습니다.
