### ISSUE TITLE
data graph 문의

### ISSUE THREAD

**Issue by Minji1234** [SNUCSE-CTA/DAF#16]
2014-14966

조교님 안녕하세요?

1) 채점할 때 주어지는 data graph G와 query graph q는 테스트로 주어진 human, human_40n과 정확히 같은 파일인지 궁금합니다.

2) average recursive call count의 경우 (새롭게 만든 .dag 파일로 얻은 결과를 test_result, 원래 주어진 코드로 생성한 .dag 파일로 얻은 결과를 original_result라 했을 때) test_result 파일에서 조회한 average recursive call count의 값은 original_result의 값보다 훨씬 크게 나오는데 python sort_result.py original_result test_result를 시행했을 때 비교 결과에서는 test1_result의 Average #recursive calls의 값이 original_result보다 훨씬 줄어든 값으로 표시됩니다.
이렇게 값이 다르게 나오는 것은 sort_result.py에서는 두 파일의 end query 중 그 값이 작은 것을 기준으로 해당 개수만큼 평균값을 구해서 그런 것 같은데 채점을 할 때는 end query 수와는 상관없이(즉 python sort_result.py를 이용한 비교값과는 상관 없이) result 파일의 총 평균 recursive call 횟수만 고려하여 반영하는지 궁금합니다.
또 두 알고리즘을 비교할 때 etl에서는 python sort_result.py를 사용하여 recursive call을 비교할 수 있다고 되어 있는데 그렇게 하면 실제로는 총 평균 recursive call 횟수가 주어진 알고리즘보다 훨씬 크게 나옴에도 불구하고 작게 나온 것으로 레포트를 작성할 수 있습니다. 레포트를 작성할 때 python sort_result.py를 사용하지 말고 result 파일에서의 값을 서로 비교하여 작성해야 하나요?

감사합니다.

**Comment by ctaroot** [comment]
1. 네 정확히 같습니다.
2. 보고서 기재 자체는 etl 에 나온 것 처럼, sort_result.py 으로 해주세요. 대략적인 성능 비교는 sort_result.py 으로 하는 것이 더 쉽기 때문에 그렇게 해주시면 됩니다.
다만 제가 sort_result 를 사용하지 않고, result 를 직접 기준으로 채점하는 이유는 result_sort.py 내부에서 돌아가는 부분을 학생들이 이해하기 직관적으로 이 값이 나오는 과정을 이해하는데 시간이 소모되기 때문에 알고리즘의 성능을 높이는데 시간을 할애하지 못해서, 바로 무슨 값인지 이해할 수 있는 result 값 자체를 사용해서 채점하기를 권장한 것입니다.

결론은 보고서 상에서의 성능 비교 자체는 result_sort.py 를 기반으로 하셔도 되고, result 값을 그냥 사용하셔도 됩니다. ( etl 에 추가했습니다. ) 성능 비교는 확실히 그냥 result 를 바로 사용합니다.
