### ISSUE TITLE
java 관련 문의

### ISSUE THREAD

**Issue by Logtic** [SNUCSE-CTA/DAF#17]
[2015-11759]
안녕하세요 조교님 
java 사용 관련해서 질문합니다.
파일을 읽을 때 저는 평소에 scanner를 사용하는데,
이게 input의 크기가 크면 굉장히 시간이 오래걸리더라고요.
Buffered InputStream을 쓰지 않고 그냥 scanner를 사용해서 생기는
시간도 혹시 채점 과정의 성능과 관련이 있을까요?

**Comment by ctaroot** [comment]
성능을 체크할 때는 dag 를 만드는 과정의 시간이 포함되지 않기 때문에 input 을 읽는 시간이 오래 걸려도 관계는 없습니다.
