### ISSUE TITLE
dag.cpp 코드에서 idxSortedData 관련

### ISSUE THREAD

**Issue by irenelynnq** [SNUCSE-CTA/DAF#19]
idxSortedData에 대한 설명은 
int* idxSortedData = NULL; //idxSortedData[l] contains the last index in sortedData such that labelData[sortedData[index]] is l
라고 되어 있고

selectRoot()에서 실제로 idxSortedData를 사용하는 방법을 살펴보니
int start = idxSortedData[label];
int end = idxSortedData[label + 1];
라고 되어 있습니다. 그런데 idxSortedData가 sortedData의 first index를 가지고 있어야 idxSortedData[label] ~ idxSortedData[label+1]이 해당 label의 data를 살펴볼 수 있게 해 주는 것이 아닌가요? 
잘 이해가 되지 않아서 질문합니다ㅠㅠ

**Comment by ctaroot** [comment]
네 start index 인데 주석에 오류가 있었습니다. start index 라고 생각하시면 될 것 같습니다.
