### ISSUE TITLE
만들어진 dag permutation은 어디다 저장을 해야할까요..?

### ISSUE THREAD

**Issue by iamsungyeonjoo** [SNUCSE-CTA/DAF#20]
[2015-11759]
조교님 정말 수고가 많으십니다. 

1.
결과적으로 완성되는 각 query에 대한 permutation은 어디다 저장을 해놓아야 하는건가요?
Main 함수 내에 자체적으로 새로운 파일을 생성해서 거기다 저장해놓아야 하나요?

2. java 템플릿에서 아래의 파일에 대한 이해가 정확한지 확인 부탁드립니다..
args[1] - data graph 정보 (템플릿 내의 human 파일)
args[2] - query graph 정보 (템플릿 내의 human_40n 파일)
args[3] - query graph 파일에 query 그래프 개수. 그러면 이 파일에는 숫자 딱 하나가 들어있는 건가요?

**Comment by ctaroot** [comment]
각 언어 마다 .sh 파일을 드렸을 텐데 그 파일에서 확인이 되듯이 각 함수마다 차례대로 stdout 스트림에 출력해주시면 .dag 파일으로 자동으로 리다이렉트해서 실행할 생각입니다. 즉, 그냥 통상적인 출력문으로 출력하시면 됩니다. 

주말인데 학생분도 수고가 많습니다.
