### ISSUE TITLE
과제 제출 문의

### ISSUE THREAD

**Issue by Minji1234** [SNUCSE-CTA/DAF#21]
안녕하세요?
etl에 과제 제출 양식이

ex >
201927354.zip
->201927354
-->main.py
-->document.doc

로 되어 있는데 다른 질문 대답에서 팀당 한 명만 소스 코드와 레포트를 제출하면 된다고 하셨습니다.
그렇다면 해당 팀의 다른 팀원이 누구인지 레포트 첫장에 써 놓고 과제 제출 디렉토리는 제출하는 팀원 학번으로 생성해서 그 팀원 메일로 최종 제출하면 되는지 궁금합니다.

감사합니다.

**Comment by ctaroot** [comment]
학번만 써주시면, 이전에 팀별로 학번을 모아둔 엑셀 파일로 제가 알아서 처리해주겠습니다. 그 부분은 신경써주시지 않아도 될 듯 합니다.
