### ISSUE TITLE
아무것도 수정하지 않은 테스트 결과

### ISSUE THREAD

**Issue by jtjun** [SNUCSE-CTA/DAF#22]
2017-17018

![image](https://user-images.githubusercontent.com/35912840/59558273-64295500-9029-11e9-8235-e350934f691b.png)

안녕하세요, 조교님 아무것도 수정하지 않은 테스트 결과에 대해 여쭤볼 것이 있어 질문 남기게 되었습니다.

제가 실행한 결과가 위와 같이 나오는데 Average elapsed time 과 Average #recursive calls 이 모두 0이 나오는 것이 정상적인 상황인가요?

감사합니다.

**Comment by ctaroot** [comment]
아뇨..? 뭔가 문제가 있는거 같습니다.
