### ISSUE TITLE
rooted DAG 의미

### ISSUE THREAD

**Issue by MadVyang** [SNUCSE-CTA/DAF#23]
2017-15049

// 이전 질문 내용이 논문에 잘 나와있어 수정했습니다.

논문에서 정의하는 rooted DAG의 의미는 정확히 한 정점만이 incoming edge가 없도록 하는 DAG를 말하는 것 같은데, data format 예시로 올려주신 3 0 1 2 의 query graph같은 경우 3과 0 모두 incoming edge가 없습니다. 이러한 DAG도 이번 과제에서 말하는 rooted DAG에 해당하는 것인가요?
정확히 이번 과제에서 rooted DAG의 의미가 무엇인지 궁금합니다.

**Comment by ctaroot** [comment]
학생분 말이 맞습니다. incomming edge 가 없는 정점은 하나여야 합니다. 잘못된 예시를 올렸네요. 수정하겠습니다.
