### ISSUE TITLE
시간 제공 문의

### ISSUE THREAD

**Issue by hephaistus** [SNUCSE-CTA/DAF#24]
2017-19313
혹시 조교 님의 채점 환경에서 제공해주신 dag.cpp로 수행하여 걸린 시간을 제공해 주실 수 있나요? 

아니면 이것이 제공해주신 ppt에 있는 값과 동일한가요...? 
 
제 환경에서 제공해주신(즉 수정하지 않은) dag.cpp 로 수행시간을 측정한 것과 ppt버전이 차이가 너무 크게 나기 때문에 문의합니다 (ppt 버전이 10배 느립니다). --> 또한 이 시간 차이가 end queries의 수에도 영향을 미치기 때문에 end queries 숫자도 다릅니다...! (recursive call 수도 다른데 이것은 왜 다른지 모르겠습니다.) 

이를 제공해 주신다면, 각자 환경 별로 시간 비율을 비교할 수 있을 듯하여 도움이 많이 될 것 같습니다!

항상 감사합니다

**Comment by ctaroot** [comment]
공지 사항을 새로 올렸습니다.
