### ISSUE TITLE
코드 수정 문의

### ISSUE THREAD

**Issue by corvuspink** [SNUCSE-CTA/DAF#25]
[2017-14605]

카피 체크 관련하여 문의드립니다.

Github에 올라와있는 dag.cpp 코드의 핵심적인 부분만 수정하고, 자료구조나 파싱 관련된 코드는 그대로 재사용하여도 표절검사 관련하여 문제가 없는지 궁금합니다.

감사합니다.

**Comment by ctaroot** [comment]
파싱 하는 부분은 그래도 하셔도 관계 없습니다.
