### ISSUE TITLE
보고서 알고리즘 설명 관련 질문

### ISSUE THREAD

**Issue by MadVyang** [SNUCSE-CTA/DAF#26]
2017-15049

보고서 3번째 항목 알고리즘 설명 부분에서,
저희가 사용한 알고리즘이 논문에 제시된 방법에서 일부만 조금 변형된 알고리즘이라면
변형된 부분만 설명하면 되나요 아니면 알고리즘 전체를 설명해야 하나요?

**Comment by ctaroot** [comment]
알고리즘을 전체도 같이 설명해야 할 것 같네요.
