### ISSUE TITLE
프로그램 실행 시간 관련 질문

### ISSUE THREAD

**Issue by gnkwon95** [SNUCSE-CTA/DAF#27]
2014-16730

조교님께서 주신 예시 ppt에서 소요되는 시간은 채점기준보다 오래걸리는데 실제 제공받은 파일을 수정하지 않고 실행해본 결과 상당부분 이미 적정 기준 내에 들어옵니다 (average search time 108ms, total time per query 112ms, average recursive call 30886, endquery 82). 프로그램이 제대로 실행된게 맞나요? 

혹시 조금 내용을 변경했는데 코드 실행 시간이 많이 개선되지 못하지만 기존 제공받은 코드 결과와 유사하면 그에 맞는 점수를 부여받게 되는가요?

**Comment by ctaroot** [comment]
제가 아키텍처 별로 실행 시간이 다를 수 있다는 사실을 간과했네요... ( 정말 기초적인 건데 죄송합니다. )
채점 기준을 다시 만들었습니다. 물론 아키텍처 별로 시간의 비율도 다를 수 있지만, 거의 유사할 것으로 생각됩니다. 일단 etl 의 비율을 기준으로 다시 코드를 작성해보시고, 채점 결과가 예상과 다르게 나오면 그 때 실험하신 컴퓨터를 들고 오시면 맞게 해드리겠습니다.
