### ISSUE TITLE
total number of found matches에 관하여

### ISSUE THREAD

**Issue by iks15174** [SNUCSE-CTA/DAF#28]
2017-11824
안녕하세요 조교님
현재 채점기준으로는 average total time per query, average recursive call count, end queries 이 세가지만 나와있습니다. 그러면 total number of found matches는 신경쓰지 않아도 괜찮나요??
감사합니다.

**Comment by ctaroot** [comment]
네 신경 쓰지 않습니다. 감사합니다.
