### ISSUE TITLE
논문에 제시된 buildDAG와 깃헙 코드의 buildDAG 알고리즘이 동일하나요?

### ISSUE THREAD

**Issue by kooyunmo** [SNUCSE-CTA/DAF#29]
2014-10470

논문상에 있는 buildDAG의 알고리즘은

1. query 그래프에 있는 정점 u 중에서 |Cini(u)| / deg(u)가 최소화되는 것을 해당 그래프의 root로 삼는다.
2. r을 구한 뒤에는 query 그래프에서 앞에서 구한 root를 가지고 BFS를 수행하되 upper level부터 lower level로 진행한다. (여기에서 level이란 root로 부터 각 정점까지의 거리를 의미한다)
3. 정점 간에 방향을 정하기 위해서 같은 level의 정점들은 같은 label끼리 묶는다.
4. Data 그래프에서 가장 드물게 등장하는 label의 그룹들이 DAG 상에서 앞에 나타나도록 순서를 정한다.
5. 각 그룹 내의 정점들은 degree에 따라 내림차순으로 정렬한다.

인데, 깃헙에 올라와있는 코드도 논문상의 알고리즘을 그대로 따른 것인가요? 아니면 저희가 개선을 위해서는 깃헙의 코드와 논문 상의 내용이 다른 부분을 찾아서 논문에 맞게 구현하여 성능을 개선해야하는건가요?

**Comment by ctaroot** [comment]
코드는 논문과 동일합니다. 논문 자체를 기반으로 개선하셔도 되고, 아예 다른 알고리즘을 작성하셔도 됩니다. dag.cpp 는 이러한 기능을 하는 파일을 만들어 달라는 예시입니다.
