### ISSUE TITLE
Permission denied가 뜹니다.

### ISSUE THREAD

**Issue by SieRaX** [SNUCSE-CTA/DAF#3]
2013-11759
안녕하세요 조교님 리눅스 환경에서
 ./daf_1min -d human -q human_40n -n 100 를 입력한 결과
bash: ./daf_1min: Permission denied 가 뜹니다. 어떻게 해야할까요??

**Comment by gywls00** [comment]
sudo daf_1min 했더니
sudo: daf_1min: command not found 라고도 뜨는데 어떻게 해야 되는 건가요??

**Comment by ctaroot** [comment]
chmod 명령어를 사용해보세요.
"chmod 777 ./daf_1min " 을 입력하고 실행해보시기 바랍니다.
