### ISSUE TITLE
Label of Vertex에 대해 질문 드립니다.

### ISSUE THREAD

**Issue by RXWE** [SNUCSE-CTA/DAF#31]
2016-18907

안녕하세요.

논문의 내용을 보면 label에 따라 묶고 정렬하는 과정이 있는 것 같은데, DAG만 만드는 것이 목적이라면 그 과정에서는 label을 고려할 필요가 없어 보입니다. label을 고려하는 것이 알고리즘의 성능을 높이기 위한 것인가요, 아니면 result permutation에 label을 고려해야 하는 조건이 있나요? 또한 query graph에서 각 vertex의 label은 특정한 패턴에 따라 부여되는 것인지 아니면 무작위로 부여되는 것인지도 궁금합니다.

**Comment by ctaroot** [comment]
label 은 무작위로 부여될 수 있습니다. label 을 정렬 기준으로 넣는 이유는 논문에서 Cini(u) 에서 데이터 그래프 상에서 쿼리 그래프 u와 같은 라벨을 가진 정점이 몇 개가 있는지 이진 탐색을 이용해서 더 빠르게 찾는 것을 가능하게 하기 위함입니다.
