### ISSUE TITLE
과제에서 구현해야 하는 부분 질문

### ISSUE THREAD

**Issue by calofmijuck** [SNUCSE-CTA/DAF#32]
2017-18570

안녕하세요, 논문을 읽다가 궁금한 점이 생겨서 질문드립니다.

논문에서 Section 3 를 보면 DAF 알고리즘에 대한 간략한 설명이 있는데요,
과제의 목표가 BuildDAG 함수를 더욱 발전시키는 것이 맞나요?

다른 부분도 추가적으로 최적화를 수행해야 하는지, 제가 잘 이해했는지 궁금합니다.

**Comment by ctaroot** [comment]
buidDag 가 수행하는 부분만 'dag' 를 생성하는 알고리즘을 개선하는 것이 맞습니다. 다른 부분은 수정하지 않으셔도 됩니다.
