### ISSUE TITLE
additional point와 C++ run.sh관련 질문드립니다

### ISSUE THREAD

**Issue by jiriboy** [SNUCSE-CTA/DAF#33]
2013-10756

알고리즘 과제4 관련하여 2가지 질문드립니다.

1. etl 공지에 보면 "If average performance is greater than original algorithm, you got a 5 additional points."라고 되어있는데, average performance라는 부분이 명확하지 않은 것 같아 설명 부탁드립니다. 올려주신 채점기준에서 3가지 항목 모두 만점을 받아야만 받을 수 있는 것인가요?

2. 올려주신 template에서 C++ run.sh에 g++ -std=c++11 main.cpp 가 아니라 그냥 g++ main.cpp 로 되어서 오류가 발생하는데 수정해서 진행해도 괜찮을까요?

**Comment by ctaroot** [comment]
아 네 그렇게 하셔도 상관 없습니다.
