### ISSUE TITLE
github에 있는 소스코드를 그대로 수행시킨 경우 질문입니다. 

### ISSUE THREAD

**Issue by tyj9327** [SNUCSE-CTA/DAF#34]
2012-12506
![image](https://user-images.githubusercontent.com/43238893/59605832-a1393880-914a-11e9-9407-4426e82c7df3.png)

그냥 깃헙의 코드를 클론받아서 수행할때, readme 파일에 있는대로라면 human_10n 파일이 있어야 하는데 없어서, 그것 대신 주어진 human_40n을 이용해서 수행해보니 오래 기다려도 결과가 나오지 않습니다. 1분이 지나면 원래 멈춰야 하는 것으로 알고 있는데 어떤 문제인지 모르겠습니다. 1분이라는 것이 실패한 경우에 1분동안 기다린다는 것인가요?

**Comment by quo1031** [comment]
human이랑 human_40을 폴더에 넣고 돌려보세요
