### ISSUE TITLE
Rooted Dag에 관한 질문입니다.

### ISSUE THREAD

**Issue by SieRaX** [SNUCSE-CTA/DAF#36]
2013-11759
안녕하세요 조교님 이번과제에서 Rooted Dag에 대해 질문이 있습니다. 
1. 저희가 뽑은 permutation이 rooted dag인지 판별하는 코드는 자체적으로 제작해야하나요?
2. 만약 Rooted dag가 아닐 경우 penalty가 있다고 하는데 정확하게 어떤 penalty가 적용되는지 알고 싶습니다. 
감사합니다.

**Comment by ctaroot** [comment]
1. rooted dag 를 판별하는 코드는 제가 직접 짭니다.
2. 아마 너무 rooted dag 인 빈도수가 높으면 고민해봐야겠고, 일부분만 rooted dag 가 된다면 그 부분만 성능이 안 좋은 값으로 대체해서 채점하지 않을까 싶네요. ( 확정은 아닙니다. )

**Comment by SieRaX** [comment]
혹시 그럼 rooted dag를 판별하는 코드도 제공해주시나요?

**Comment by SieRaX** [comment]
> 1. rooted dag 를 판별하는 코드는 제가 직접 짭니다.
> 2. 아마 너무 rooted dag 인 빈도수가 높으면 고민해봐야겠고, 일부분만 rooted dag 가 된다면 그 부분만 성능이 안 좋은 값으로 대체해서 채점하지 않을까 싶네요. ( 확정은 아닙니다. )
1번에서 혹시 그럼 rooted dag를 판별하는 코드도 제공해주시나요?

**Comment by ctaroot** [comment]
아뇨 그건 채점할 때만 사용합니다.
