### ISSUE TITLE
자바로 테스트 하는 법

### ISSUE THREAD

**Issue by icasud1** [SNUCSE-CTA/DAF#37]
2008-12407

Main.java를 이용해서 *.dag를 만들고
만들어진 dag file을 daf_1min을 통해 결과를 확인하면 되는지 궁금합니다.
가령 제가 만든 dag file이 human.dag라고 하면
"./daf_1min -d human -q human_40n -a human.dag -n 100"
을 실행해서 나오는 결과로 평가받는 게 맞나요?

**Comment by ctaroot** [comment]
네 맞습니다.
