### ISSUE TITLE
Algorithm을 선택한 이유

### ISSUE THREAD

**Issue by YejiAhn** [SNUCSE-CTA/DAF#39]
2015-15838
보고서 요구사항 중에 Please describe your algorithm / write the reason why you choose that algorithm 이라는 항목이 있는데, 
DAG를 만드는 알고리즘을 여러 가지 시도해보고 DAF에 넣었을 때 결과가 가장 좋은 것을 최종 결과로 선택한 경우, 이렇게 여러 알고리즘을 시도해본 결과 가장 좋은 결과가 나왔다는 식으로 경험적으로 해당 알고리즘의 선택 이유를 증명해도 될까요?  reason을 설명할 때 이 정도로 충분한지 아니면 선택한 DAG의 어떤 특성이 DAF 알고리즘의 성능을 높였는지에 대한 설명이 필요한지 궁금합니다.

**Comment by ctaroot** [comment]
실험적인 증명도 충분히 설득력이 있다고 생각합니다. 
그렇게 결과가 나온 이유도 생각해서 있으면 좋겠지만, 실험적인 증명 자체만 넣어도 근거가 될 수 있다고 생각합니다.
