### ISSUE TITLE
그래프 환경 질문.

### ISSUE THREAD

**Issue by jinsun1117** [SNUCSE-CTA/DAF#4]
2014-12308

조교님 안녕하세요 
그래프 인풋 관련하여 몇 가지 질문이 있습니다. 
1. 데이터/쿼리 그래프에서 다음과 같은 상황이 발생할 수 있는지 궁금합니다
    1) 한 vertex에서 자기 자신을 가리키는 loop
    2) 쿼리 그래프가 데이터보다 적은 label을 보유할 수 있는지(예: 그래프에는 A,B,C,D총 4가지 label이 있는데 쿼리는 A,B,C로만 되는지)
    3) 쿼리 그래프에 같은 label이 중복될 수 있는지
2. human_40n의 내용은
    t   graph No.    Vertex count   Edge count
    vertexa vertex1 vertex2 vertex3 ...

    where vertex 1,2,3 are connected to vertexa

    로 이해했습니다. 

    그러나 중간에 보면 (line 311)
     22 26 4 4 6 21 23 처럼 중복된 vertice( 4 & 4)가 있는 것 같습니다. 

     혹시 human_40n에 대해 잘못 이해한 게 있는지 궁금합니다.

3. 혹시 dag output format이 어떻게 되는지 설명해주실 수 있을까요? 전체적으로 인풋을 읽고 아웃풋을 쓰는 과정이 어려워서 헤매고 있습니다.

감사합니다.

추가적으로, 
논문을 보면  "...optimize the CS by repeating DAG-graph DP with alternating qD and qD-1"(p.7) 라고 되어있습니다. 그러나 Figure 5 (a)의 경우처럼 leaf가 여러개 있는 경우 qD-1을 어떻게 만드느지, 이때 root는 무엇을 사용해서 refinement를 하는지 궁금합니다. 

레포트 작성 시, 팀 전체가 같은 레포트를 써도 되는지, 개별로 레포트는 따로 해야되는지 궁금합니다.

**Comment by ctaroot** [comment]
관련 ppt 를 etl 에 올렸는데 확인해보세요.

**Comment by ctaroot** [comment]
인풋 포맷에 대한 자료를 게시판에 올렸으니 읽어보시면 전부 답변이 될 것 같습니다.
