### ISSUE TITLE
label 관련 질문

### ISSUE THREAD

**Issue by minty99** [SNUCSE-CTA/DAF#40]
2017-12690

DAF 알고리즘이 해결하려는 문제인 subgraph matching과 label의 존재가 무슨 관계가 있는지 모르겠습니다. 질문 #31 에서 label이 이진 탐색을 용이하게 위해서라고 답변해 주셨는데 그렇다면 아무 의미 없이 성능만을 위해 존재하는 것인가요? vertex의 label이라는 게 실제로 어떤 의미를 갖나요?

**Comment by ctaroot** [comment]
label 은 일단 subgraph isomorphism 문제에 내제되어 있는 특성입니다. query node 와 data node 간의 label 이 동일한 경우에만 matching 이 가능하도록 만든 것이죠.
