### ISSUE TITLE
github 코드 구현 범위에 대한 질문

### ISSUE THREAD

**Issue by KRKimDongWoo** [SNUCSE-CTA/DAF#42]
2017-17319

github에서 받아 구현중인 DAG.cpp에 논문에 포함된 최적화 기능이 모두 구현되어 있는 것 같지 않은 것 같아 질문드립니다. candidat set optimization과 같은 다른 최적화 작업들은 다른 파일에서 이미 구현이 되어 있는 건가요?

**Comment by ctaroot** [comment]
그 부분은 ./daf_1min 에 포함되어 있습니다.

**Comment by KRKimDongWoo** [comment]
@ctaroot 감사합니다!
