### ISSUE TITLE
DAG의 표현의 유일성에 관한 문의

### ISSUE THREAD

**Issue by sylee0124** [SNUCSE-CTA/DAF#43]
2015-18764

1. 
한 DAG를 vertex의 linear sequence로 표현하여 DAF에 input으로 제공하는데 이때 그 DAG로부터 만들어지는 vertex의 linear sequence는 유일한가요?

2. 
DAF에 저희가 선택한 DAG의 linear sequence를 입력으로 주는 걸로 알고 있습니다.

이때 저희가 해야 하는 게 DAG를 잘 뽑아서 DAF의 성능을 개선시키는 건지,

아니면 DAG 뽑는 방식은 논문 방식(깃헙 방식) 그대로 냅두고 (만일 1번에서 질문드린것 처럼 여러 sequence로 표현이 가능하다면) 그 DAG를 다른 방식의 linear sequence로 표현하여 DAF의 성능을 개선시켜도 되는건지

궁금합니다.

감사합니다.

**Comment by ctaroot** [comment]
1. 아뇨 유일하지 않죠. { (0,1), (1,2), (2,3), (3,0) } 그래프에서 0 1 2 3 과 0 2 1 3 은 같은 dag 를 가집니다. 
2. 전자입니다.
