### ISSUE TITLE
기본 뼈대 실행으로부터의 문제

### ISSUE THREAD

**Issue by 9lung** [SNUCSE-CTA/DAF#44]
2015-17069

dag.cpp / main.cpp 를 이용하여 human.dag를 만들었고, 예시처럼 daf1_min 을 실행한 결과, 기존 알고리즘 방식으로는 결과가 나오는데 answer를 넣는 형식으로는 몇초있다가 종료되면서 다음과 같은 결과가 나옵니다. 전에 있던 issue에서 폴더에 따로 넣어보라고 하셔서 해봤지만 작동되지 않습니다. 혹시 원인을 알 수 있을까요?[
![캡처](https://user-images.githubusercontent.com/22000316/59685018-2dfcf880-9216-11e9-96b9-f42272bbcbbe.PNG)
![캡처2](https://user-images.githubusercontent.com/22000316/59685020-2e958f00-9216-11e9-97cb-5f9125097b3a.PNG)

](url)

**Comment by ctaroot** [comment]
어... 이렇게만 봐서는 뭐가 문제인지 잘 모르겠는데 혹시 컴퓨터를 들고 와 주실 수 있나요.
