### ISSUE TITLE
main.cpp 질문

### ISSUE THREAD

**Issue by Minji1234** [SNUCSE-CTA/DAF#45]
안녕하세요?

1) 과제를 제출할 때 main.cpp 파일을 제출하라고 되어 있는데 앞서 답변하신 내용처럼 dag.h와 수정한 dag.cpp와 기존 main.cpp를 합치면 g++ -std=c++11 main.cpp dag.cpp -o program으로는 컴파일이 되지 않습니다.
채점하실 때는 dag.cpp 부분을 뺀 g++ -std=c++11 main.cpp -o program으로 컴파일하신다고 생각하면 될까요?

2) 당연한 것이겠지만 채점하실 때 채점 폴더에 human, human_40n, daf_1min이 함께 들어있다고 생각하면 되는지 궁금합니다.

감사합니다.

**Comment by ctaroot** [comment]
1. 깃의 코드는 예시이기 때문에 run.sh 형태로 컴파일 하지만, ( 컴파일러 버전은 공지 사항 대로 ) 저런 형태의 컴파일을 원하신다면 보고서에 명시해주세요.
2. 네
