### ISSUE TITLE
Grading Policy 질문

### ISSUE THREAD

**Issue by dnjstlr0503** [SNUCSE-CTA/DAF#46]
2014-19797

조교님 안녕하세요, Grading Policy 질문 드립니다.

기존의 HW4 requirements에서는 "If average performance is greater than original algorithm, you got a 5 additional points." 명시되어있는데요.

나중에 올려주신 Grading policy를 보면 average total time per Query가 원래 알고리즘의 0.9배보다 적어야 만점인 걸로 바뀌었습니다.

여전히 가산점 5점(performance가 더 좋을 때)이 유효한 것인가요?

**Comment by ctaroot** [comment]
기존 채점 기준은 적용되지 않습니다.
