### ISSUE TITLE
daf_1min이 time limit 없이 실행되는 문제

### ISSUE THREAD

**Issue by ysmjp** [SNUCSE-CTA/DAF#47]
2011-13330
Ubuntu 16.04LTS에서 프로그래밍하고 있는데,
daf_1min을 실행시켰을 때 1분이 초과해도 프로그램이 정상 종료되지 않습니다.
```./daf_1min -d human -q human_40n -a human_40.dag -n 100```와 같이 실행시켰는데
어떻게 해야 1분의 시간 제한을 걸 수 있는 지 궁금합니다.

**Comment by minty99** [comment]
각각의 테스트 케이스에 대해 1분이라서 훨씬 오래 걸립니다.
