### ISSUE TITLE
보고서 알고리즘 설명 범위 질문드립니다.

### ISSUE THREAD

**Issue by timedilation** [SNUCSE-CTA/DAF#49]
2014-18200

조교님께,
#26 에서 논문 알고리즘의 일부를 변형시킨 경우 전체 알고리즘에 대한 설명 또한 필요하다고 답변하셨는데, 이 때 전체 알고리즘이라는 것이 DAG build 이후에 이를 사용하여 어떻게 subgraph matching까지 진행하는지까지 포함하는 것인가요? 아니면 DAG를 어떻게 만드는지에 대한 알고리즘만인가요?
감사합니다.

**Comment by ctaroot** [comment]
dag 를 어떻게 만드는 지만 포함하는 알고리즘 입니다.
