### ISSUE TITLE
코드 구현 관련 문의입니다!

### ISSUE THREAD

**Issue by Hohoro15** [SNUCSE-CTA/DAF#5]
2015-12377

안녕하세요 조교님,

채점기준에 보면 
![Screenshot from 2019-06-13 10-39-23](https://user-images.githubusercontent.com/29170598/59397447-9e93b780-8dc7-11e9-922c-737c69f5b502.png)
35 포인트 중 5포인트가 original algorithm보다 성능이 좋을 때 부여된다고 되어있는데,
그러면 논문에 쓰인 알고리즘 즉, dag.cpp로 제공해주신 코드를 modify하여 성능을 향상시키는 것이 이 숙제의 목표인가요?

office hour 때 여쭤봤을 때는 논문에 있는 그대로 구현해도 된다고 하셨는데, 그러면 언어를 c++로 선택한 사람들은 그냥 dag.cpp를 거의 갖다써도 되는건지, 아니라면 어느정도까지만 유사하게 작성해야하는건지 궁금합니다!
그리고 논문을 그대로 구현한다면 만점에 가깝게 받을 수 있는건가요?

그리고 시간 비교는 언어마다 다르게 비교하실건지 궁금합니다!

**Comment by ctaroot** [comment]
제가 좀 더 구체적으로 작성해서 오늘 올리겠습니다.
