### ISSUE TITLE
변경한 코드로도 같은 루트가 선택되는 경우에 대한 질문

### ISSUE THREAD

**Issue by tyj9327** [SNUCSE-CTA/DAF#50]
2012-12506
안녕하세요!
저희가 select root의 알고리즘을 변경했는데 시뮬레이션을 돌려보니 수행시간은 변화가 있었지만 recursive call의 개수에 변화가 없습니다. 아마도 변경된 알고리즘으로도 같은 루트가 선택된 것 같은데, 이러한 경우도 인정이 되는 것인가요?

**Comment by ctaroot** [comment]
다른 알고리즘이면 괜찮습니다.
