### ISSUE TITLE
JAVA에서 args표현에 관하여 문의드립니다.

### ISSUE THREAD

**Issue by Dorvin** [SNUCSE-CTA/DAF#51]
2017-10488
안녕하세요 조교님!
JAVA에서 args인자에 대한 주석에 오류가 있는것 같아 이슈에 올립니다.
C나 C++과 달리 JAVA에서는 args[0]에 첫번째 인자가 들어가는 것으로 알고 있습니다.
따라서
        //args[0] : name of data query file
        //args[1] : name of query graph file
        //args[2] : the number of query in query graph file
이렇게 보고 코딩을 했고, 올바른 결과를 도출했습니다. 
이 형식대로 제출을 하고자 하는데 혹시 이상이 있다면 답변해주시면 감사하겠습니다! :)

**Comment by ctaroot** [comment]
주석 복사 붙여넣기 하는 과정에서 문제가 실수가 있었네요. 결과만 맞다면 그대로 보내셔도 됩니다.
