### ISSUE TITLE
sort_result.py의 결과가 result의 결과와 다릅니다.

### ISSUE THREAD

**Issue by icasud1** [SNUCSE-CTA/DAF#52]
2008-12407

안녕하세요.
python sort_result.py result1 result2를 했을 때
recursive calls(0.0)나 elapsed time의 값(0.286)이 이상하게 나옵니다.
vim으로 result를 열어보면 다른 결과(per query: 1.723, recursive call:513.295)가 나오는데
왜 이런 건가요?

**Comment by ctaroot** [comment]
듣기만 해서는 잘 모르겠네요. 혹시 해당 화면 캡처해서 메일로 보내주실 수 있나요.
