### ISSUE TITLE
제출할 때의 형식과 관련하여 질문드립니다!

### ISSUE THREAD

**Issue by koyrkr** [SNUCSE-CTA/DAF#53]
2015-17261

제출할 때 보면 main 파일만 제출하라고 해주셨는데요,

코드가 길어지다보니 나누지 않으면 main 파일 코드가 너무 길어져서 가독성이 떨어지는 것 같아서요!

혹시 이럼에도 불구하고 모든 코드를 다 main 파일로 다 합쳐서 제출해야하는 것이 맞나요?

항상 수고가 많으십니다, 감사합니다 :)

**Comment by ctaroot** [comment]
합쳐서 제출하지 않으셔도 됩니다. 대신 c++ 일 경우에는 번거롭겠지만, 소스 파일 단위로 하면 링킹을 따로 해야 해서 자동 채점이 어려울 수 있느니, 헤더 파일 단위로 분리해주시면 감사하겠습니다.
