### ISSUE TITLE
과제4 요구사항 질문

### ISSUE THREAD

**Issue by kanghc0217** [SNUCSE-CTA/DAF#8]
2017-16342

안녕하세요, 질문 드립니다.

과제 4에서 하고자 하는 것이 dag.cpp의 buildDAG()를 자신(팀)의 알고리즘으로 구현하라는 것이 맞나요? 그런데 제출해야 하는 것은 main.cpp 하나이니까 github의 1) dag.h, 2) buildDAG()를 수정한 dag.cpp, 3) main.cpp의 내용을.. 제출해야하는 main.cpp 하나에 전부 박아 넣으면 되는건가요?

**Comment by ctaroot** [comment]
네. main.cpp 를 돌렸을 때 데이터 그래프와 쿼리 그래프를 읽어서 dag 를 만드는 과정까지 전부 수행이 되어야 합니다.
