### ISSUE TITLE
buildDAG에 따라 solved가 달라질 수 있는지

### ISSUE THREAD

**Issue by uyw4687** [SNUCSE-CTA/DAF#9]
2015-13700

안녕하세요.
buildDAG에서 간단한 수정을 한 후 결과적으로 DAG까지는 바뀌는 걸 확인했습니다.
그리고 결과를 봤는데 이전 결과랑 비슷하지만 일부 결과에서 solved가 다른 걸 확인했습니다. 원래 알고리즘대로 하면 solved(1)인데 바꾼 알고리즘대로 하면 0이 되는 것도 있고 반대의 경우도 있습니다.
정상적인 경우인지 궁금합니다.
아니라면 저희 알고리즘이 틀려서 buildDAG 부분을 다시 고쳐야 하는지 아니면 DAG가 달라서 '시간 내에' 못찾을 수도 있는 건지 알고 싶습니다.

그리고 기본적으로 sorting 기반으로 알고리즘이 짜여 있는 것 같은데 얼마나 고치는 게 유효한 것으로 인정이 되는지 궁금합니다.
아예 다른 접근을 해야 하는지 아니면 원래 있는 알고리즘에서 한두줄 고치는 것도 유효한 것으로 인정이 되는 건지가 궁금합니다.(예를 들어, sorting 기준만 변경)

**Comment by ctaroot** [comment]
[1] 네, 물론 dag 를 어떤 방식으로 만드냐에 따라서 시간 내에 모든 embedding 을 찾을 수도 있고, 찾지 못할 수도 있기 때문에 solved 는 변경될 수 있습니다.
[2] sorting 기준이 다른 것은 과정 자체가 다르기 때문에 다른 알고리즘이라고 생각할 수 있습니다.
